### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by kdvmgn** [BeauNouvelle/ShimmerView-Swift#1]
…Pods/ShimmerSwift/Shimmer/ShimmeringLayer.swift: 37: 20: Fatal error: Use of unimplemented initializer 'init(layer:)' for class 'ShimmerSwift.ShimmeringLayer'

The app crash occurred when user scrolling view, while a shimmering view is shimmering

**Comment by westonmiller** [comment]
I get the same thing when trying to change the text of a label, even if I set `isShimmering = false` before changing it

**Comment by jackdewhurst** [comment]
I had the same problem on device rotation, forked the project and fixed it here - https://github.com/jackdewhurst/ShimmerSwift

Fixed by adding an override for `init(layer: Any)` in **ShimmeringLayer.swift**

```
public override init(layer: Any) {
     super.init(layer: layer)
}
```

I've also reduced the minimum deployment target to 9.0 and allowed subclassing of **ShimmeringView.swift**.

**Comment by PanajotisMaroungas** [comment]
This PR should fix the crash 
https://github.com/BeauNouvelle/ShimmerSwift/pull/4
